### ISSUE TITLE
Admin password retrieval

### ISSUE THREAD

**Issue by superdingo101** [l4rm4nd/VoucherVault#11]
**Describe the bug**
Is there a way to recover the admin password? 

**Affected version**
0.1.6, but really the docs should be updated to include the method of password retrieval. 

**To Reproduce**
1. Spin up instance through "docker compose up" using docker-compose.yml
2. Restart server later with "docker compose down && docker compose up"

**Expected behavior**
A method called out in the docs to recover the admin password at a later date.

**Comment by l4rm4nd** [comment]
Hey @superdingo101 ,

the [README](https://github.com/l4rm4nd/VoucherVault?tab=readme-ov-file#-usage) outlines it quite clearly. 

The admin password is auto-generated and displayed once in the container logs. You have to retrieve the admin password at the first time spinning up the container. Otherwise, the password is lost.

If so, you can remove the `./volume-data/database/db.sqlite3` database file and start freshly. Ensure to note down the admin password this time.

Alternatively, if you already have started using VoucherVault but did not note down the admin password, you can still recover. VoucherVault is developed with the Django framework. Therefore, you can use [native Django tooling](https://docs.djangoproject.com/en/5.0/topics/auth/default/#changing-passwords) to create a new superuser or reset a user's password.

To do so, follow these steps:

````
# exec into the docker container
docker exec -it vouchervault bash

# reset the password
python manage.py changepassword admin
````

Afterwards, you can authenticate with the newly set password.

**Comment by l4rm4nd** [comment]
May read the wiki too.

Just created it now and will add new entries over the next days.

https://github.com/l4rm4nd/VoucherVault/wiki/02-%E2%80%90-Authentication-and-User-Management#change-user-passwords
