### ISSUE TITLE
[FEATURE] Set expiry date to non-expiring

### ISSUE THREAD

**Issue by moostmartijn** [l4rm4nd/VoucherVault#16]
**Describe the solution you'd like**
At this moment you have to set an expiry date for giftcards. I do have some giftcars which don't have an expiry date so I would like to set it to non-expiring.

**Comment by l4rm4nd** [comment]
Hi @moostmartijn 

many thanks for reaching out.

I've already thought about leaving the expiry date optional. However, the backend likely still needs a date nonetheless. Otherwise, I would have to touch many different areas of code right now (create-item, edit-item, expiry notifications and maybe more).

**An easy fix**: The user may leave the expiry date on the frontend empty, while creating or editing an item. The backend would then just define a future expiry date like in 20 years. This way though, it is not really unset or optional. I don't like this idea and would rather have the user supply a self-chosen "fictive" expiry date.

I'll have to think about it a bit more. Will come back to this issue.

In the meantime, I suggest choosing an expiry date to your liking. Maybe a future year you'd definitely like to redeem it. In this case, you would still get expiry notifications about such an item to remind you about its existence.
