### ISSUE TITLE
[FEATURE] Sort items on inventory

### ISSUE THREAD

**Issue by pixpaws** [l4rm4nd/VoucherVault#38]
In the inventory page, items are not sorted by default. It should be very nice if items can be sorted, to improve readability. 

Maybe those fields should be orderable :

- Expiry date (ASC, DESC)
- Issuer (ASC, DESC)
- Available sold (ASC, DESC)
- [...]

**Comment by l4rm4nd** [comment]
Hi @pixpaws,

there was a bug introduced that broke the existing type filtering. Is now fixed in https://github.com/l4rm4nd/VoucherVault/commit/b8a1416ee49bb36dc511ddb62a3934283fed15e8.

I also added sorting by expiry date. The inventory will now apply auto-filtering and list items, which will soon expire first.

Sorting by issuer does not make much sense imo. However, you can filter items by issuer name by using the `Search keyword` field. 

Cheers!
